version: 0.2

phases:
  install:
    commands:
      - echo Installing frontend dependencies...
      - npm install

  build:
    commands:
      - echo Building frontend...
      - npm run build   # creates dist/

artifacts:
  files:
    - '**/*'
  base-directory: dist
